#host_vars/srv010.yml
---
mysql_databases:
  - name: wordpress

mysql_users:
  - name: wordpress
    password: LVFMjKT49R1hxqjBAzDy
    priv: "*.*:ALL,GRANT"

rhbase_firewall_allow_services:
  - http
  - https

php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-gd
  - php-mbstring
  - php-pdo
  - php-pecl-apcu
  - php-xml
